development:
  adapter: postgresql
  encoding: unicode
  database: fitbit_development
  pool: 5
  username: Zach
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: fitbit_test
  pool: 5
  username: Zach
  password:
  timeout: 5000